CanvasesのSwaggerタグをつける
TeamDotArt/dotart-backend pull request #49
Opened 2021-10-27 07:14 UTC by keykimu

#46 の実装

2021-10-28 16:23 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
> +  async findAll(): Promise<FindAllCanvasResponse[]> {
ユーザのキャンバスなので他人が他人の全キャンバス見れたらおかしい

2021-10-28 16:33 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
> +    @Param('canvasId') canvasId: string,
パラメータもDtoからにする #28 を参考に

2021-10-28 16:33 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
> +    @Param('canvasName') canvasName: string,
パラメータもDtoからにする #28 を参考に

2021-10-28 16:34 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
> +  @Patch(':canvasId')
Param使わないのにパラメータの設定がある

2021-10-28 16:34 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
> +  @ApiParam({
上記と同じく

2021-10-28 16:35 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
> +  @Delete(':canvasId')
上記と同じく

2021-10-28 16:35 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
> +  @ApiParam({
上記と同じく

2021-10-28 16:36 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +    const decoded: DecodedDto = jwt_decode(req.headers.authorization);
helperの `jwtDecoded` を使用する

2021-10-28 16:42 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +    const user: User = await this.usersService.findOne(decoded.id);
現状使用してないので謎だが多分userIdを引き出すのに使うものだと思うので
`getUserIdById`を使った方がいい

2021-10-28 16:42 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +        userId: data.userId,
上記で取得したuserIdを利用する

2021-10-28 16:45 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +    const decoded: DecodedDto = jwt_decode(req.headers.authorization);
helperの `jwtDecoded` を使用する

2021-10-28 16:46 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +  async removeCanvasData(req: FastifyRequest): Promise<RemoveCanvasResponse> {
updateCanvasとremoveCanvasDataって明記揺れがあるので統一する

2021-10-28 16:47 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +    const decoded: DecodedDto = jwt_decode(req.headers.authorization);
helperの `jwtDecoded` を使用する

2021-10-28 16:48 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +    const user: User = await this.usersService.findOne(decoded.id);
getUserIdByIdを使った方がいい

2021-10-28 16:48 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +    const user: User = await this.usersService.findOne(decoded.id);
getUserIdByIdを使った方がいい

2021-10-28 16:49 UTC, RimlTempest commented on src/canvases/dto/create-canvas.dto.ts
> +export class CreateCanvasRequest {
必須値なものはちゃんと`IsNotEmpty`をつける

2021-10-28 16:51 UTC, RimlTempest commented on src/canvases/dto/delete-canvas.dto.ts
> +  @IsNotEmpty()
ResponseなのにIsNotEmptyついているのは理由がある(?)

2021-10-28 16:52 UTC, RimlTempest commented on src/canvases/dto/findAll-canvas.dto.ts
> +  id: Canvas['id'];
レスポンスに固有IDは含めない

2021-10-28 16:53 UTC, RimlTempest commented on src/canvases/dto/update-canvas.dto.ts
> +export class UpdateCanvasRequest {
必須要素には`IsNotEmpty`をつける

2021-10-28 16:54 UTC, RimlTempest commented on src/canvases/entities/canvase.entity.ts
> +  //子要素系
子要素ではないし、いわゆる外部キー制約用のものなので必要ない

2021-10-28 16:55 UTC, RimlTempest requested changes
コメントしました

2021-10-29 01:33 UTC, keykimu commented on src/canvases/canvases.controller.ts
> +  async findAll(): Promise<FindAllCanvasResponse[]> {
自分のキャンバスだけを全表示すればいい感じ？

2021-10-29 02:35 UTC, keykimu commented on src/canvases/canvases.service.ts
> +    const decoded: DecodedDto = jwt_decode(req.headers.authorization);
#28 実装前にブランチ切ってたからないわ
ブランチ作り直したほうがいいかな？

2021-10-29 02:40 UTC, keykimu commented on src/canvases/dto/delete-canvas.dto.ts
> +  @IsNotEmpty()
コピって消すの忘れてたっぽい

2021-10-31 09:02 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
> +  async findAll(): Promise<FindAllCanvasResponse[]> {
そう

2021-10-31 09:05 UTC, RimlTempest commented on src/canvases/canvases.service.ts
>      return this.prisma.canvases.findMany();
ユーザー以外のキャンパスも全取得できるのはおかしい

2021-10-31 09:09 UTC, RimlTempest commented on src/canvases/dto/update-canvas.dto.ts
> +export class UpdateCanvasRequest {
更新時キャンバス名変更が必須なのはおかしい

2021-10-31 09:11 UTC, RimlTempest requested changes
コメントしました

2021-11-02 10:27 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +    canvases.map((element) => {
オプションだったり他に方法はない？
違和感がすごくある
https://docs.nestjs.com/recipes/prisma

2021-11-02 10:28 UTC, RimlTempest commented on src/canvases/canvases.service.ts
> +    canvases.map((element) => {
オプションだったり他に方法はない？
違和感がすごくある
https://docs.nestjs.com/recipes/prisma

2021-11-02 11:16 UTC, RimlTempest commented
mapなのが問題なのではなくてカウンタを使うやり方に違和感がある
filterとかでやった方がよくない？

2021-11-02 11:17 UTC, RimlTempest commented
> mapなのが問題なのではなくてカウンタを使うやり方に違和感がある
> filterとかでやった方がよくない？

2021-11-02 11:20 UTC, RimlTempest commented
それかfindManyのoptionで検索対象を
userIdかつcanvasIdとかにできればもっと違和感なく書けると思う

2021-11-04 00:49 UTC, RimlTempest commented on src/canvases/canvases.controller.ts
>  // TODO: ApiResponseを記載する
記載しているのでこのコメントいらなそう

2021-11-04 00:57 UTC, RimlTempest commented on src/canvases/dto/findAll-canvas.dto.ts
> +import { Constants } from 'src/common/constants';
上記でGithubActionsに怒られている通り`IsNotEmpry`が使われていないので使わないなら消す

2021-11-04 00:59 UTC, RimlTempest commented on src/canvases/entities/canvase.entity.ts
> -export class Canvase {}
ファイル名がtypoでcanvase.entity.tsになっているので`canvas.entity.ts`に修正する

2021-11-04 01:00 UTC, RimlTempest requested changes
コメントしました

2021-11-04 01:44 UTC, RimlTempest approved these changes
LGTM

2021-11-04 01:44 UTC, merged